apiVersion: apps/v1
kind: Deployment
metadata:
 name: cw-app-deploy
 labels:
  name: cw-app-deploy
  app: cw-app
spec:
 replicas: 3
 selector:
  matchLabels:
   name: cw-app-pod
   app: cw-app
 template:
  metadata:
   name: cw-app-pod
   labels:
    name: cw-app-pod
    app: cw-app
  spec:
   containers:
    - name: cw-app
      image: indikul/cw_app:final
      ports:
       - containerPort: 5000
      