apiVersion: v1
kind: Service
metadata:
 name: cw-app-service
 labels:
  name: cw-app-service
  app: cw-app
spec:
 type: LoadBalancer
 ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004
 selector:
   name: cw-app-pod
   app: cw-app